# Generated by Django 5.2.4 on 2025-07-13 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('careers', '0004_job_application_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='status',
        ),
    ]
